import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import * as bcrypt from 'bcrypt';
import { randomBytes } from 'node:crypto';
import { PrismaService } from '../prisma/prisma.service';
import type { CurrentUserIdentity } from '../auth/current-user.interface';
import { CreateApiKeyDto, CreatePermissionDto, CreateRoleDto, UpdateRoleDto, UpdateUserDto } from './dto';

@Injectable()
export class UserManagementService {
  constructor(private readonly prisma: PrismaService) {}
  users() { return this.prisma.appUser.findMany({ include: { Role: true }, orderBy: { Name: 'asc' } }); }
  async updateUser(id: string, dto: UpdateUserDto, actor: CurrentUserIdentity) { const user = await this.prisma.appUser.findUnique({ where: { Id: id } }); if (!user) throw new NotFoundException('User not found'); if (user.SsoObjectId === actor.username && dto.isActive === false) throw new ConflictException('You cannot deactivate your own account'); return this.prisma.appUser.update({ where: { Id: id }, data: { RoleId: dto.roleId, IsActive: dto.isActive, UpdatedBy: actor.username }, include: { Role: true } }); }
  roles() { return this.prisma.appRole.findMany({ include: { Permissions: true, _count: { select: { Users: true } } }, orderBy: { Name: 'asc' } }); }
  createRole(dto: CreateRoleDto, actor: CurrentUserIdentity) { return this.prisma.appRole.create({ data: { Name: dto.name.toUpperCase(), Description: dto.description, CreatedBy: actor.username, Permissions: { connect: dto.permissionIds.map((Id) => ({ Id })) } }, include: { Permissions: true } }); }
  async updateRole(id: string, dto: UpdateRoleDto, actor: CurrentUserIdentity) { const role = await this.prisma.appRole.findUnique({ where: { Id: id } }); if (!role) throw new NotFoundException('Role not found'); if (role.IsSystem && dto.name && dto.name.toUpperCase() !== role.Name) throw new ConflictException('System role name cannot be changed'); return this.prisma.appRole.update({ where: { Id: id }, data: { Name: dto.name?.toUpperCase(), Description: dto.description, UpdatedBy: actor.username, ...(dto.permissionIds ? { Permissions: { set: dto.permissionIds.map((Id) => ({ Id })) } } : {}) }, include: { Permissions: true } }); }
  async deleteRole(id: string) { const role = await this.prisma.appRole.findUnique({ where: { Id: id }, include: { _count: { select: { Users: true } } } }); if (!role) throw new NotFoundException('Role not found'); if (role.IsSystem || role._count.Users) throw new ConflictException('System roles or assigned roles cannot be deleted'); await this.prisma.appRole.delete({ where: { Id: id } }); return { deleted: true, id }; }
  permissions() { return this.prisma.appPermission.findMany({ orderBy: { Action: 'asc' } }); }
  createPermission(dto: CreatePermissionDto) { if (!/^MTC\.[A-Z0-9_.]+$/.test(dto.action)) throw new BadRequestException('Permission action must use the MTC.* namespace'); return this.prisma.appPermission.create({ data: { Action: dto.action, Description: dto.description } }); }
  async deletePermission(id: string) { const permission = await this.prisma.appPermission.findUnique({ where: { Id: id }, include: { Roles: true } }); if (!permission) throw new NotFoundException('Permission not found'); if (permission.Roles.length) throw new ConflictException('Assigned permission cannot be deleted'); await this.prisma.appPermission.delete({ where: { Id: id } }); return { deleted: true, id }; }
  apiKeys() { return this.prisma.apiKey.findMany({ select: { Id: true, Name: true, Prefix: true, IsActive: true, Permissions: true, ExpiresAt: true, LastUsedAt: true, CreatedAt: true, CreatedBy: true, RevokedAt: true, RevokedBy: true }, orderBy: { CreatedAt: 'desc' } }); }
  async createApiKey(dto: CreateApiKeyDto, actor: CurrentUserIdentity) { const valid = await this.prisma.appPermission.count({ where: { Action: { in: dto.permissions } } }); if (valid !== new Set(dto.permissions).size) throw new BadRequestException('One or more API key permissions are invalid'); const secret = `mtc_${randomBytes(30).toString('base64url')}`; const prefix = secret.slice(0, 12); const record = await this.prisma.apiKey.create({ data: { Name: dto.name, Prefix: prefix, SecretHash: await bcrypt.hash(secret, 12), Permissions: [...new Set(dto.permissions)], ExpiresAt: dto.expiresAt ? new Date(dto.expiresAt) : null, CreatedBy: actor.username } }); return { id: record.Id, name: record.Name, prefix, secret, warning: 'Copy this secret now. It will not be shown again.' }; }
  async revokeApiKey(id: string, actor: CurrentUserIdentity) { const key = await this.prisma.apiKey.findUnique({ where: { Id: id } }); if (!key) throw new NotFoundException('API key not found'); return this.prisma.apiKey.update({ where: { Id: id }, data: { IsActive: false, RevokedAt: new Date(), RevokedBy: actor.username } }); }
}
