import { createAsyncThunk, createSlice, type PayloadAction } from '@reduxjs/toolkit';
import { api, type ApiEnvelope, type Pagination, saveBlob } from '../utils/api';

export interface InventoryItem { Id: string; ItemCode: string; Name: string; Brand: string | null; Model: string | null; SerialNumber: string | null; Unit: string; AddressLocation: string; CurrentBalance: string; MinimumStock: string; IsActive: boolean; DiscontinuedAt: string | null; DiscontinueReason: string | null; CreatedAt: string; CreatedBy: string; UpdatedAt: string; UpdatedBy: string | null }
export interface ItemQuery { page: number; limit: number; search: string; active?: boolean; lowStock?: boolean; address?: string; sortBy?: string; sortOrder?: 'asc'|'desc' }
export interface ItemInput { itemCode: string; name: string; brand?: string; model?: string; serialNumber?: string; unit: string; addressLocation: string; minimumStock: number; openingBalance?: number; referenceDoc?: string; notes?: string }
interface State { data: InventoryItem[]; selected: InventoryItem | null; query: ItemQuery; pagination: Pagination; loading: boolean; saving: boolean; error: string | null }
const initialState: State = { data: [], selected: null, query: { page: 1, limit: 50, search: '' }, pagination: { page: 1, limit: 50, totalItems: 0, totalPages: 0 }, loading: false, saving: false, error: null };
const errorMessage = (e: unknown) => e instanceof Error ? e.message : 'Unexpected error';
export const fetchItems = createAsyncThunk('items/list', async (query: ItemQuery, { rejectWithValue }) => { try { return await api.get<ApiEnvelope<InventoryItem[]>>('/items', query); } catch (e) { return rejectWithValue(errorMessage(e)); } });
export const createItem = createAsyncThunk('items/create', async (input: ItemInput, { rejectWithValue }) => { try { return await api.post<ApiEnvelope<InventoryItem>>('/items', input); } catch (e) { return rejectWithValue(errorMessage(e)); } });
export const updateItem = createAsyncThunk('items/update', async ({ id, input }: { id: string; input: Partial<ItemInput> }, { rejectWithValue }) => { try { return await api.patch<ApiEnvelope<InventoryItem>>(`/items/${id}`, input); } catch (e) { return rejectWithValue(errorMessage(e)); } });
export const archiveItem = createAsyncThunk('items/archive', async ({ id, reason }: { id: string; reason: string }, { rejectWithValue }) => { try { return await api.post<ApiEnvelope<InventoryItem>>(`/items/${id}/archive`, { reason }); } catch (e) { return rejectWithValue(errorMessage(e)); } });
export const reactivateItem = createAsyncThunk('items/reactivate', async (id: string, { rejectWithValue }) => { try { return await api.post<ApiEnvelope<InventoryItem>>(`/items/${id}/reactivate`, {}); } catch (e) { return rejectWithValue(errorMessage(e)); } });
export const exportItems = createAsyncThunk('items/export', async (query: ItemQuery, { rejectWithValue }) => { try { saveBlob(await api.blob(`/items/export?search=${encodeURIComponent(query.search)}`), 'mtc-items.xlsx'); } catch (e) { return rejectWithValue(errorMessage(e)); } });
export const previewImport = createAsyncThunk('items/importPreview', async (file: File, { rejectWithValue }) => { try { const data = new FormData(); data.append('file', file); return await api.upload<ApiEnvelope<{ valid: boolean; rows: Record<string, unknown>[]; errors: Array<{ rowNumber: number; field: string; message: string }>; summary: Record<string, number> }>>('/imports/items/preview', data); } catch (e) { return rejectWithValue(errorMessage(e)); } });
export const commitImport = createAsyncThunk('items/importCommit', async (rows: Record<string, unknown>[], { rejectWithValue }) => { try { return await api.post<ApiEnvelope<{ imported: number }>>('/imports/items/commit', { rows }, crypto.randomUUID()); } catch (e) { return rejectWithValue(errorMessage(e)); } });
const slice = createSlice({ name: 'items', initialState, reducers: { setItemQuery(state, action: PayloadAction<Partial<ItemQuery>>) { state.query = { ...state.query, ...action.payload }; }, setSelectedItem(state, action: PayloadAction<InventoryItem | null>) { state.selected = action.payload; } }, extraReducers(builder) { builder.addCase(fetchItems.pending, (s) => { s.loading = true; s.error = null; }).addCase(fetchItems.fulfilled, (s, a) => { s.loading = false; s.data = a.payload.data; if (a.payload.meta) s.pagination = a.payload.meta; }).addCase(fetchItems.rejected, (s, a) => { s.loading = false; s.error = a.payload as string; }).addMatcher((a) => [createItem.pending.type, updateItem.pending.type, archiveItem.pending.type, reactivateItem.pending.type].includes(a.type), (s) => { s.saving = true; }).addMatcher((a) => [createItem.fulfilled.type, updateItem.fulfilled.type, archiveItem.fulfilled.type, reactivateItem.fulfilled.type, createItem.rejected.type, updateItem.rejected.type, archiveItem.rejected.type, reactivateItem.rejected.type].includes(a.type), (s) => { s.saving = false; }); } });
export const { setItemQuery, setSelectedItem } = slice.actions; export default slice.reducer;
