import { createAsyncThunk, createSlice, type PayloadAction } from '@reduxjs/toolkit';
import { api, type ApiEnvelope, type Pagination } from '../utils/api';
import type { InventoryItem } from './itemsSlice';
export type TransactionType = 'OPENING_BALANCE'|'STOCK_IN'|'STOCK_OUT'|'SCRAP'|'STOCK_OPNAME_DIFF'|'REVERSAL';
export interface Ledger { Id: string; ItemId: string; TransactionDate: string; TransactionType: TransactionType; ReferenceDoc: string; BalanceBefore: string; QtyIn: string; QtyOut: string; BalanceAfter: string; CreatedBy: string; ActorDisplayName?: string; Notes: string | null; Item: Pick<InventoryItem,'Model'|'Name'|'AddressLocation'|'Unit'> }
export interface LedgerQuery { page: number; limit: number; search: string; transactionType?: TransactionType; itemId?: string; actor?: string; from?: string; to?: string }
interface State { data: Ledger[]; query: LedgerQuery; pagination: Pagination; loading: boolean; saving: boolean; error: string | null }
const initialState: State = { data: [], query: { page: 1, limit: 50, search: '' }, pagination: { page: 1, limit: 50, totalItems: 0, totalPages: 0 }, loading: false, saving: false, error: null };
const msg = (e: unknown) => e instanceof Error ? e.message : 'Unexpected error';
export const fetchLedger = createAsyncThunk('stock/list', async (query: LedgerQuery, { rejectWithValue }) => { try { return await api.get<ApiEnvelope<Ledger[]>>('/stock/ledger', query); } catch (e) { return rejectWithValue(msg(e)); } });
export const fetchTransactions = createAsyncThunk('stock/transactions', async (query: LedgerQuery, { rejectWithValue }) => { try { return await api.get<ApiEnvelope<Ledger[]>>('/stock/transactions', query); } catch (e) { return rejectWithValue(msg(e)); } });
export const mutateStock = createAsyncThunk('stock/mutate', async ({ type, input }: { type: 'in'|'out'|'scrap'; input: { itemId: string; quantity: number; referenceDoc: string; notes?: string } }, { rejectWithValue }) => { try { return await api.post<ApiEnvelope<unknown>>(`/stock/${type}`, input, crypto.randomUUID()); } catch (e) { return rejectWithValue(msg(e)); } });
const slice = createSlice({ name: 'stock', initialState, reducers: { setLedgerQuery(s, a: PayloadAction<Partial<LedgerQuery>>) { s.query = { ...s.query, ...a.payload }; } }, extraReducers(b) { b.addCase(fetchLedger.pending, (s) => { s.loading = true; }).addCase(fetchLedger.fulfilled, (s,a) => { s.loading = false; s.data = a.payload.data; if (a.payload.meta) s.pagination = a.payload.meta; }).addCase(fetchLedger.rejected, (s,a) => { s.loading = false; s.error = a.payload as string; }).addCase(fetchTransactions.pending, (s) => { s.loading = true; }).addCase(fetchTransactions.fulfilled, (s,a) => { s.loading = false; s.data = a.payload.data; if (a.payload.meta) s.pagination = a.payload.meta; }).addCase(fetchTransactions.rejected, (s,a) => { s.loading = false; s.error = a.payload as string; }).addCase(mutateStock.pending, (s) => { s.saving = true; }).addCase(mutateStock.fulfilled, (s) => { s.saving = false; }).addCase(mutateStock.rejected, (s,a) => { s.saving = false; s.error = a.payload as string; }); } });
export const { setLedgerQuery } = slice.actions; export default slice.reducer;
